/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabbar: typeof import('./components/AppTabbar.vue')['default']
    AuthorTag: typeof import('./components/AuthorTag.vue')['default']
    BabyForm: typeof import('./components/family/BabyForm.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    CheckinSheet: typeof import('./components/plan/CheckinSheet.vue')['default']
    ChipGroup: typeof import('./components/ChipGroup.vue')['default']
    CopyFallback: typeof import('./components/report/CopyFallback.vue')['default']
    DateBar: typeof import('./components/DateBar.vue')['default']
    DayTimeline: typeof import('./components/charts/DayTimeline.vue')['default']
    FeedingTimeline: typeof import('./components/plan/FeedingTimeline.vue')['default']
    InviteSheet: typeof import('./components/family/InviteSheet.vue')['default']
    LibraryCard: typeof import('./components/plan/LibraryCard.vue')['default']
    LogItem: typeof import('./components/LogItem.vue')['default']
    LogSheet: typeof import('./components/LogSheet.vue')['default']
    NoteThread: typeof import('./components/NoteThread.vue')['default']
    PageNav: typeof import('./components/PageNav.vue')['default']
    ProgressRing: typeof import('./components/plan/ProgressRing.vue')['default']
    RadarChart: typeof import('./components/charts/RadarChart.vue')['default']
    ReportBlockCard: typeof import('./components/report/ReportBlockCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StagePanel: typeof import('./components/plan/StagePanel.vue')['default']
    SyncStatus: typeof import('./components/SyncStatus.vue')['default']
    TaskCard: typeof import('./components/plan/TaskCard.vue')['default']
    TaskEditSheet: typeof import('./components/plan/TaskEditSheet.vue')['default']
    TimeField: typeof import('./components/TimeField.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VoiceSheet: typeof import('./components/VoiceSheet.vue')['default']
  }
}
